version: '3'

services:
  reverse-proxy:
    image: traefik:v2.9
    command: --configfile=/plugins-local/src/github.com/traceableai/traceableai_traefik_plugin/local/traefik.yaml
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../:/plugins-local/src/github.com/traceableai/traceableai_traefik_plugin

  echo-service:
    image: jmalloc/echo-server
    environment:
      - LOG_HTTP_HEADERS=true
      - LOG_HTTP_BODY=true

  grpc-service:
    build: ./grpc
    labels:
      - traefik.http.services.grpc-service.loadbalancer.server.scheme=h2c
    ports:
      - "8090:8090"
