name: Test

on: [push, pull_request]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.19"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test ./...

  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start Docker Compose stack
        run: cd local && docker-compose up -d reverse-proxy

      - name: Wait on startup
        run: sleep 45

      - name: Ensure startup without errors
        run: | 
          cd local
          docker-compose logs reverse-proxy > logs.txt
          ./test.sh logs.txt